// Generated by CoffeeScript 1.9.2
'use strict';
var _, config, env, fs, path, userConfig;

fs = require('fs');

path = require('path');

_ = require('lodash');

env = process.env.NODE_ENV || 'development';

const extension = '.js';
config = _.merge(require(`./env/all${extension}`), require('./env/' + env + extension || {}));

if (process.env.USER && env !== 'production') {
    userConfig = './user/' + process.env.USER + extension;
    if (fs.existsSync(path.join(path.join(__dirname, userConfig)))) {
        config = _.merge(config, require(userConfig));
    } else {
        console.log('User config not found, defaulting to development.coffee');
    }
}

module.exports = config;
